authors:
- Kevin Breit
dependencies: {}
description: An Ansible collection for managing the Cisco Meraki Dashboard
documentation: ''
homepage: ''
issues: https://github.com/CiscoDevNet/ansible-meraki/issues
license:
- GPL-3.0-only
name: meraki
namespace: cisco
readme: README.md
repository: https://github.com/CiscoDevNet/ansible-meraki
tags:
- networking
- wireless
- firewall
- switching
- cisco
version: 2.4.1
build_ignore:
- '*tar.gz'
- '*.DS_Store'
- '*.json'
- 'venv'
- '.vscode'
- '.gitignore'
- '.env'
- '.github'
- 'tests/output/'
