plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    meraki_admin:
      description: Manage administrators in the Meraki cloud
      name: meraki_admin
      namespace: ''
      version_added: '2.6'
    meraki_config_template:
      description: Manage configuration templates in the Meraki cloud
      name: meraki_config_template
      namespace: ''
      version_added: '2.7'
    meraki_content_filtering:
      description: Edit Meraki MX content filtering policies
      name: meraki_content_filtering
      namespace: ''
      version_added: null
    meraki_device:
      description: Manage devices in the Meraki cloud
      name: meraki_device
      namespace: ''
      version_added: null
    meraki_firewalled_services:
      description: Edit firewall policies for administrative network services
      name: meraki_firewalled_services
      namespace: ''
      version_added: null
    meraki_intrusion_prevention:
      description: Manage intrustion prevention in the Meraki cloud
      name: meraki_intrusion_prevention
      namespace: ''
      version_added: null
    meraki_malware:
      description: Manage Malware Protection in the Meraki cloud
      name: meraki_malware
      namespace: ''
      version_added: null
    meraki_management_interface:
      description: Configure Meraki management interfaces
      name: meraki_management_interface
      namespace: ''
      version_added: 1.1.0
    meraki_mr_l3_firewall:
      description: Manage MR access point layer 3 firewalls in the Meraki cloud
      name: meraki_mr_l3_firewall
      namespace: ''
      version_added: null
    meraki_ms_link_aggregation:
      description: Manage link aggregations on MS switches
      name: meraki_ms_link_aggregation
      namespace: ''
      version_added: 1.2.0
    meraki_mx_l3_firewall:
      description: Manage MX appliance layer 3 firewalls in the Meraki cloud
      name: meraki_mx_l3_firewall
      namespace: ''
      version_added: null
    meraki_mx_l7_firewall:
      description: Manage MX appliance layer 7 firewalls in the Meraki cloud
      name: meraki_mx_l7_firewall
      namespace: ''
      version_added: null
    meraki_mx_site_to_site_firewall:
      description: Manage MX appliance firewall rules for site-to-site VPNs
      name: meraki_mx_site_to_site_firewall
      namespace: ''
      version_added: 1.0.0
    meraki_mx_uplink:
      description: Manage uplinks on Meraki MX appliances
      name: meraki_mx_uplink
      namespace: ''
      version_added: 1.1.0
    meraki_nat:
      description: Manage NAT rules in Meraki cloud
      name: meraki_nat
      namespace: ''
      version_added: null
    meraki_network:
      description: Manage networks in the Meraki cloud
      name: meraki_network
      namespace: ''
      version_added: null
    meraki_organization:
      description: Manage organizations in the Meraki cloud
      name: meraki_organization
      namespace: ''
      version_added: null
    meraki_site_to_site_vpn:
      description: Manage AutoVPN connections in Meraki
      name: meraki_site_to_site_vpn
      namespace: ''
      version_added: 1.1.0
    meraki_snmp:
      description: Manage organizations in the Meraki cloud
      name: meraki_snmp
      namespace: ''
      version_added: null
    meraki_ssid:
      description: Manage wireless SSIDs in the Meraki cloud
      name: meraki_ssid
      namespace: ''
      version_added: null
    meraki_static_route:
      description: Manage static routes in the Meraki cloud
      name: meraki_static_route
      namespace: ''
      version_added: null
    meraki_switch_access_list:
      description: Manage access lists for Meraki switches in the Meraki cloud
      name: meraki_switch_access_list
      namespace: ''
      version_added: 0.1.0
    meraki_switch_stack:
      description: Modify switch stacking configuration in Meraki.
      name: meraki_switch_stack
      namespace: ''
      version_added: 1.3.0
    meraki_switch_storm_control:
      description: Manage storm control configuration on a switch in the Meraki cloud
      name: meraki_switch_storm_control
      namespace: ''
      version_added: 0.0.1
    meraki_switchport:
      description: Manage switchports on a switch in the Meraki cloud
      name: meraki_switchport
      namespace: ''
      version_added: null
    meraki_syslog:
      description: Manage syslog server settings in the Meraki cloud.
      name: meraki_syslog
      namespace: ''
      version_added: null
    meraki_vlan:
      description: Manage VLANs in the Meraki cloud
      name: meraki_vlan
      namespace: ''
      version_added: null
    meraki_webhook:
      description: Manage webhooks configured in the Meraki cloud
      name: meraki_webhook
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.3.2
