name: Changelog
on:
  pull_request:


jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
